/*
Manifest Maestro

Renders Kubernetes manifests with the help of various tools such as Helm and Kustomize.

API version: v1.2.0
Contact: e.rieb@posteo.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the HelmListChartsItemVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelmListChartsItemVersion{}

// HelmListChartsItemVersion struct for HelmListChartsItemVersion
type HelmListChartsItemVersion struct {
	Version string `json:"version"`
	AdditionalProperties map[string]interface{}
}

type _HelmListChartsItemVersion HelmListChartsItemVersion

// NewHelmListChartsItemVersion instantiates a new HelmListChartsItemVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelmListChartsItemVersion(version string) *HelmListChartsItemVersion {
	this := HelmListChartsItemVersion{}
	this.Version = version
	return &this
}

// NewHelmListChartsItemVersionWithDefaults instantiates a new HelmListChartsItemVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmListChartsItemVersionWithDefaults() *HelmListChartsItemVersion {
	this := HelmListChartsItemVersion{}
	return &this
}

// GetVersion returns the Version field value
func (o *HelmListChartsItemVersion) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *HelmListChartsItemVersion) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *HelmListChartsItemVersion) SetVersion(v string) {
	o.Version = v
}

func (o HelmListChartsItemVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmListChartsItemVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HelmListChartsItemVersion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelmListChartsItemVersion := _HelmListChartsItemVersion{}

	err = json.Unmarshal(data, &varHelmListChartsItemVersion)

	if err != nil {
		return err
	}

	*o = HelmListChartsItemVersion(varHelmListChartsItemVersion)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHelmListChartsItemVersion struct {
	value *HelmListChartsItemVersion
	isSet bool
}

func (v NullableHelmListChartsItemVersion) Get() *HelmListChartsItemVersion {
	return v.value
}

func (v *NullableHelmListChartsItemVersion) Set(val *HelmListChartsItemVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableHelmListChartsItemVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmListChartsItemVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmListChartsItemVersion(val *HelmListChartsItemVersion) *NullableHelmListChartsItemVersion {
	return &NullableHelmListChartsItemVersion{value: val, isSet: true}
}

func (v NullableHelmListChartsItemVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmListChartsItemVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


