/*
Manifest Maestro

Renders Kubernetes manifests with the help of various tools such as Helm and Kustomize.

API version: v1
Contact: e.rieb@posteo.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the HelmGetChartMetadataActionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelmGetChartMetadataActionResponse{}

// HelmGetChartMetadataActionResponse struct for HelmGetChartMetadataActionResponse
type HelmGetChartMetadataActionResponse struct {
	DefaultValues map[string]interface{} `json:"defaultValues"`
	AdditionalProperties map[string]interface{}
}

type _HelmGetChartMetadataActionResponse HelmGetChartMetadataActionResponse

// NewHelmGetChartMetadataActionResponse instantiates a new HelmGetChartMetadataActionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelmGetChartMetadataActionResponse(defaultValues map[string]interface{}) *HelmGetChartMetadataActionResponse {
	this := HelmGetChartMetadataActionResponse{}
	this.DefaultValues = defaultValues
	return &this
}

// NewHelmGetChartMetadataActionResponseWithDefaults instantiates a new HelmGetChartMetadataActionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmGetChartMetadataActionResponseWithDefaults() *HelmGetChartMetadataActionResponse {
	this := HelmGetChartMetadataActionResponse{}
	return &this
}

// GetDefaultValues returns the DefaultValues field value
func (o *HelmGetChartMetadataActionResponse) GetDefaultValues() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.DefaultValues
}

// GetDefaultValuesOk returns a tuple with the DefaultValues field value
// and a boolean to check if the value has been set.
func (o *HelmGetChartMetadataActionResponse) GetDefaultValuesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.DefaultValues, true
}

// SetDefaultValues sets field value
func (o *HelmGetChartMetadataActionResponse) SetDefaultValues(v map[string]interface{}) {
	o.DefaultValues = v
}

func (o HelmGetChartMetadataActionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmGetChartMetadataActionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["defaultValues"] = o.DefaultValues

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HelmGetChartMetadataActionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"defaultValues",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelmGetChartMetadataActionResponse := _HelmGetChartMetadataActionResponse{}

	err = json.Unmarshal(data, &varHelmGetChartMetadataActionResponse)

	if err != nil {
		return err
	}

	*o = HelmGetChartMetadataActionResponse(varHelmGetChartMetadataActionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "defaultValues")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHelmGetChartMetadataActionResponse struct {
	value *HelmGetChartMetadataActionResponse
	isSet bool
}

func (v NullableHelmGetChartMetadataActionResponse) Get() *HelmGetChartMetadataActionResponse {
	return v.value
}

func (v *NullableHelmGetChartMetadataActionResponse) Set(val *HelmGetChartMetadataActionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHelmGetChartMetadataActionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmGetChartMetadataActionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmGetChartMetadataActionResponse(val *HelmGetChartMetadataActionResponse) *NullableHelmGetChartMetadataActionResponse {
	return &NullableHelmGetChartMetadataActionResponse{value: val, isSet: true}
}

func (v NullableHelmGetChartMetadataActionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmGetChartMetadataActionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


