/*
Manifest Maestro

Renders Kubernetes manifests with the help of various tools such as Helm and Kustomize.

API version: v1.2.0
Contact: e.rieb@posteo.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the HelmListChartsItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelmListChartsItem{}

// HelmListChartsItem struct for HelmListChartsItem
type HelmListChartsItem struct {
	Name string `json:"name"`
	Versions []HelmListChartsItemVersion `json:"versions"`
	AdditionalProperties map[string]interface{}
}

type _HelmListChartsItem HelmListChartsItem

// NewHelmListChartsItem instantiates a new HelmListChartsItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelmListChartsItem(name string, versions []HelmListChartsItemVersion) *HelmListChartsItem {
	this := HelmListChartsItem{}
	this.Name = name
	this.Versions = versions
	return &this
}

// NewHelmListChartsItemWithDefaults instantiates a new HelmListChartsItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmListChartsItemWithDefaults() *HelmListChartsItem {
	this := HelmListChartsItem{}
	return &this
}

// GetName returns the Name field value
func (o *HelmListChartsItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HelmListChartsItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HelmListChartsItem) SetName(v string) {
	o.Name = v
}

// GetVersions returns the Versions field value
func (o *HelmListChartsItem) GetVersions() []HelmListChartsItemVersion {
	if o == nil {
		var ret []HelmListChartsItemVersion
		return ret
	}

	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value
// and a boolean to check if the value has been set.
func (o *HelmListChartsItem) GetVersionsOk() ([]HelmListChartsItemVersion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Versions, true
}

// SetVersions sets field value
func (o *HelmListChartsItem) SetVersions(v []HelmListChartsItemVersion) {
	o.Versions = v
}

func (o HelmListChartsItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmListChartsItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["versions"] = o.Versions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HelmListChartsItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"versions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelmListChartsItem := _HelmListChartsItem{}

	err = json.Unmarshal(data, &varHelmListChartsItem)

	if err != nil {
		return err
	}

	*o = HelmListChartsItem(varHelmListChartsItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "versions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHelmListChartsItem struct {
	value *HelmListChartsItem
	isSet bool
}

func (v NullableHelmListChartsItem) Get() *HelmListChartsItem {
	return v.value
}

func (v *NullableHelmListChartsItem) Set(val *HelmListChartsItem) {
	v.value = val
	v.isSet = true
}

func (v NullableHelmListChartsItem) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmListChartsItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmListChartsItem(val *HelmListChartsItem) *NullableHelmListChartsItem {
	return &NullableHelmListChartsItem{value: val, isSet: true}
}

func (v NullableHelmListChartsItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmListChartsItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


