/*
Manifest Maestro

Renders Kubernetes manifests with the help of various tools such as Helm and Kustomize.

API version: v1.2.0
Contact: e.rieb@posteo.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the HelmChartMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelmChartMetadata{}

// HelmChartMetadata struct for HelmChartMetadata
type HelmChartMetadata struct {
	Name string `json:"name"`
	Version string `json:"version"`
	AppVersion *string `json:"appVersion,omitempty"`
	Dependencies []HelmChartMetadata `json:"dependencies"`
	AdditionalProperties map[string]interface{}
}

type _HelmChartMetadata HelmChartMetadata

// NewHelmChartMetadata instantiates a new HelmChartMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelmChartMetadata(name string, version string, dependencies []HelmChartMetadata) *HelmChartMetadata {
	this := HelmChartMetadata{}
	this.Name = name
	this.Version = version
	this.Dependencies = dependencies
	return &this
}

// NewHelmChartMetadataWithDefaults instantiates a new HelmChartMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmChartMetadataWithDefaults() *HelmChartMetadata {
	this := HelmChartMetadata{}
	return &this
}

// GetName returns the Name field value
func (o *HelmChartMetadata) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HelmChartMetadata) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HelmChartMetadata) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *HelmChartMetadata) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *HelmChartMetadata) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *HelmChartMetadata) SetVersion(v string) {
	o.Version = v
}

// GetAppVersion returns the AppVersion field value if set, zero value otherwise.
func (o *HelmChartMetadata) GetAppVersion() string {
	if o == nil || IsNil(o.AppVersion) {
		var ret string
		return ret
	}
	return *o.AppVersion
}

// GetAppVersionOk returns a tuple with the AppVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmChartMetadata) GetAppVersionOk() (*string, bool) {
	if o == nil || IsNil(o.AppVersion) {
		return nil, false
	}
	return o.AppVersion, true
}

// HasAppVersion returns a boolean if a field has been set.
func (o *HelmChartMetadata) HasAppVersion() bool {
	if o != nil && !IsNil(o.AppVersion) {
		return true
	}

	return false
}

// SetAppVersion gets a reference to the given string and assigns it to the AppVersion field.
func (o *HelmChartMetadata) SetAppVersion(v string) {
	o.AppVersion = &v
}

// GetDependencies returns the Dependencies field value
func (o *HelmChartMetadata) GetDependencies() []HelmChartMetadata {
	if o == nil {
		var ret []HelmChartMetadata
		return ret
	}

	return o.Dependencies
}

// GetDependenciesOk returns a tuple with the Dependencies field value
// and a boolean to check if the value has been set.
func (o *HelmChartMetadata) GetDependenciesOk() ([]HelmChartMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dependencies, true
}

// SetDependencies sets field value
func (o *HelmChartMetadata) SetDependencies(v []HelmChartMetadata) {
	o.Dependencies = v
}

func (o HelmChartMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmChartMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	if !IsNil(o.AppVersion) {
		toSerialize["appVersion"] = o.AppVersion
	}
	toSerialize["dependencies"] = o.Dependencies

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HelmChartMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"version",
		"dependencies",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelmChartMetadata := _HelmChartMetadata{}

	err = json.Unmarshal(data, &varHelmChartMetadata)

	if err != nil {
		return err
	}

	*o = HelmChartMetadata(varHelmChartMetadata)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "version")
		delete(additionalProperties, "appVersion")
		delete(additionalProperties, "dependencies")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHelmChartMetadata struct {
	value *HelmChartMetadata
	isSet bool
}

func (v NullableHelmChartMetadata) Get() *HelmChartMetadata {
	return v.value
}

func (v *NullableHelmChartMetadata) Set(val *HelmChartMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableHelmChartMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmChartMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmChartMetadata(val *HelmChartMetadata) *NullableHelmChartMetadata {
	return &NullableHelmChartMetadata{value: val, isSet: true}
}

func (v NullableHelmChartMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmChartMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


