/*
Manifest Maestro

Renders Kubernetes manifests with the help of various tools such as Helm and Kustomize.

API version: v1.2.0
Contact: e.rieb@posteo.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the HelmListChartVersionsActionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelmListChartVersionsActionResponse{}

// HelmListChartVersionsActionResponse struct for HelmListChartVersionsActionResponse
type HelmListChartVersionsActionResponse struct {
	Items []string `json:"items"`
	AdditionalProperties map[string]interface{}
}

type _HelmListChartVersionsActionResponse HelmListChartVersionsActionResponse

// NewHelmListChartVersionsActionResponse instantiates a new HelmListChartVersionsActionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelmListChartVersionsActionResponse(items []string) *HelmListChartVersionsActionResponse {
	this := HelmListChartVersionsActionResponse{}
	this.Items = items
	return &this
}

// NewHelmListChartVersionsActionResponseWithDefaults instantiates a new HelmListChartVersionsActionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmListChartVersionsActionResponseWithDefaults() *HelmListChartVersionsActionResponse {
	this := HelmListChartVersionsActionResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *HelmListChartVersionsActionResponse) GetItems() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *HelmListChartVersionsActionResponse) GetItemsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *HelmListChartVersionsActionResponse) SetItems(v []string) {
	o.Items = v
}

func (o HelmListChartVersionsActionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmListChartVersionsActionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HelmListChartVersionsActionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelmListChartVersionsActionResponse := _HelmListChartVersionsActionResponse{}

	err = json.Unmarshal(data, &varHelmListChartVersionsActionResponse)

	if err != nil {
		return err
	}

	*o = HelmListChartVersionsActionResponse(varHelmListChartVersionsActionResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHelmListChartVersionsActionResponse struct {
	value *HelmListChartVersionsActionResponse
	isSet bool
}

func (v NullableHelmListChartVersionsActionResponse) Get() *HelmListChartVersionsActionResponse {
	return v.value
}

func (v *NullableHelmListChartVersionsActionResponse) Set(val *HelmListChartVersionsActionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHelmListChartVersionsActionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmListChartVersionsActionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmListChartVersionsActionResponse(val *HelmListChartVersionsActionResponse) *NullableHelmListChartVersionsActionResponse {
	return &NullableHelmListChartVersionsActionResponse{value: val, isSet: true}
}

func (v NullableHelmListChartVersionsActionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmListChartVersionsActionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


