/*
Manifest Maestro

Renders Kubernetes manifests with the help of various tools such as Helm and Kustomize.

API version: v1
Contact: e.rieb@posteo.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the HelmListChartsAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelmListChartsAction{}

// HelmListChartsAction struct for HelmListChartsAction
type HelmListChartsAction struct {
	Reference HelmRepositoryReference `json:"reference"`
	AdditionalProperties map[string]interface{}
}

type _HelmListChartsAction HelmListChartsAction

// NewHelmListChartsAction instantiates a new HelmListChartsAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelmListChartsAction(reference HelmRepositoryReference) *HelmListChartsAction {
	this := HelmListChartsAction{}
	this.Reference = reference
	return &this
}

// NewHelmListChartsActionWithDefaults instantiates a new HelmListChartsAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmListChartsActionWithDefaults() *HelmListChartsAction {
	this := HelmListChartsAction{}
	return &this
}

// GetReference returns the Reference field value
func (o *HelmListChartsAction) GetReference() HelmRepositoryReference {
	if o == nil {
		var ret HelmRepositoryReference
		return ret
	}

	return o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value
// and a boolean to check if the value has been set.
func (o *HelmListChartsAction) GetReferenceOk() (*HelmRepositoryReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reference, true
}

// SetReference sets field value
func (o *HelmListChartsAction) SetReference(v HelmRepositoryReference) {
	o.Reference = v
}

func (o HelmListChartsAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmListChartsAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reference"] = o.Reference

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HelmListChartsAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reference",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelmListChartsAction := _HelmListChartsAction{}

	err = json.Unmarshal(data, &varHelmListChartsAction)

	if err != nil {
		return err
	}

	*o = HelmListChartsAction(varHelmListChartsAction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "reference")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHelmListChartsAction struct {
	value *HelmListChartsAction
	isSet bool
}

func (v NullableHelmListChartsAction) Get() *HelmListChartsAction {
	return v.value
}

func (v *NullableHelmListChartsAction) Set(val *HelmListChartsAction) {
	v.value = val
	v.isSet = true
}

func (v NullableHelmListChartsAction) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmListChartsAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmListChartsAction(val *HelmListChartsAction) *NullableHelmListChartsAction {
	return &NullableHelmListChartsAction{value: val, isSet: true}
}

func (v NullableHelmListChartsAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmListChartsAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


